CREATE TABLE EMPRESAS (
    CODEMP VARCHAR(2) NOT NULL PRIMARY KEY,
    NOMEMP VARCHAR(150) NOT NULL,
    NOMREP VARCHAR(100) NOT NULL,
    CARREP VARCHAR(50),
    DIRECC VARCHAR(50),
    NOMCIU VARCHAR(50),
    -- CODUSU VARCHAR(30) NOT NULL,
    FECULT DATE,
    RUCREP VARCHAR(25) NOT NULL,
    ESTADO BIT,
    EMAIL VARCHAR(50)
);

-- CODUS1 => CODIGO DEL USUARIO
CREATE TABLE USUARIOS (
    CODUSU VARCHAR(25) NOT NULL PRIMARY KEY,
    NOMUSU VARCHAR(200) NOT NULL,
    TIPUSU VARCHAR(50),
    CLAUSU VARCHAR(150) NOT NULL,
    FECING DATE,
    FECEXP DATE,
    ESTADO BIT,
    EMAIL VARCHAR(50),
);

CREATE TABLE EMPLEADOS (
    codusu VARCHAR(10),
    nomusu VARCHAR(255),
    TIPUSU VARCHAR(50),
    enfcod VARCHAR(10) PRIMARY KEY,
    enfnom VARCHAR(255),
    enfape VARCHAR(255),
    enfnomape VARCHAR(255),
    enffecnac DATE,
    enffecing DATE,
    enfsex VARCHAR(1),
    enfciu VARCHAR(255),
    enfpro VARCHAR(255),
    enfdir VARCHAR(255),
    enftel VARCHAR(255),
    enfcel VARCHAR(255),
    enfemail VARCHAR(255),
    enfcargo VARCHAR(255),
    enfestado VARCHAR(255)
);

CREATE TABLE CLASE_ARTICULOS (
    CODCLA VARCHAR(20) NOT NULL PRIMARY KEY,
    NOMCLA VARCHAR(150) NOT NULL,
    CODUS1 VARCHAR(25) NOT NULL,
    FECULT DATE,
    FOREIGN KEY (CODUS1) REFERENCES USUARIOS(CODUS1)
);

CREATE TABLE IVA_ARTICULOS (
    CODIVA VARCHAR(10) NOT NULL PRIMARY KEY,
    NOMIVA VARCHAR(60) NOT NULL,
    PORIVA NUMERIC(25) NOT NULL,
    CODUS1 VARCHAR(25) NOT NULL,
    FECULT DATE,
    FOREIGN KEY (CODUS1) REFERENCES USUARIOS(CODUS1)
);

CREATE TABLE UNIDADESM_ARTICULOS (
    CODUNI VARCHAR(10) NOT NULL PRIMARY KEY,
    NOMUNI VARCHAR(60) NOT NULL,
    CODUS1 VARCHAR(25) NOT NULL,
    FECULT DATE,
    FOREIGN KEY (CODUS1) REFERENCES USUARIOS(CODUS1)
);

CREATE TABLE ARTICULOS (
    CODART VARCHAR(10) NOT NULL PRIMARY KEY,
    NOMART VARCHAR(60) NOT NULL,
    CODCLA VARCHAR(20) NOT NULL,
    CODUNI VARCHAR(10) NOT NULL,
    EXIACT NUMERIC(20, 4),
    COSPRO NUMERIC(20, 4),
    ULTCOS NUMERIC(20, 4),
    CODUCO BIT,
    FOREIGN KEY (CODCLA) REFERENCES CLASE_ARTICULOS(CODCLA),
    FOREIGN KEY (CODUNI) REFERENCES UNIDADESM_ARTICULOS(CODUNI)
);

CREATE TABLE tIPO_tRANSACCION (
    CODTRA VARCHAR(10) NOT NULL PRIMARY KEY,
    NOMTRA VARCHAR(60) NOT NULL,
    signo VARCHAR(1)
);

CREATE TABLE KARDEX (
    CODART VARCHAR(10) NOT NULL PRIMARY KEY,
    NOMART VARCHAR(150) NOT NULL,
    CODCLA VARCHAR(20) NOT NULL PRIMARY KEY,
    CODUNI VARCHAR(10) NOT NULL PRIMARY KEY,
    EXIACT NUMBER(20, 4) COSPRO NUMBER(20, 4),
    ULTCOS NUMBER(20, 4),
    COSTUNI NUMBER(20, 2),
    CODUCO BIT,
    FOREIGN KEY (CODART) REFERENCES ARTICULOS(CODART),
    FOREIGN KEY (CODCLA) REFERENCES CLASE_ARTICULOS(CODCLA),
    FOREIGN KEY (CODUNI) REFERENCES UNIDADESM_ARTICULOS(CODUNI),
);